name: Deploy to Bunny.net

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Deploy to Bunny.net
        uses: jlarmstrongiv/bunny-launcher-github-action@main
        with:
          accessKey: ${{ secrets.BUNNY_ACCESS_KEY }}
